version: "3.9"

services:
  app:
    container_name: budgettracker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    environment:
      APP_KEY:
      DB_HOST:
      DB_DATABASE:
      DB_USERNAME:
      DB_PASSWORD:
    working_dir: /var/www/html
    networks:
      - budgettracker

  nginx:
    image: nginx:1-alpine
    container_name: budgettracker-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - budgettracker

networks:
  budgettracker:
    driver: bridge
